name: Deploy to Hostinger (FTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Preflight secrets check
        run: |
          missing=0
          [ -z "${{ secrets.FTP_SERVER }}" ] && echo "Missing required secret: FTP_SERVER" && missing=1
          [ -z "${{ secrets.FTP_USERNAME }}" ] && echo "Missing required secret: FTP_USERNAME" && missing=1
          [ -z "${{ secrets.FTP_PASSWORD }}" ] && echo "Missing required secret: FTP_PASSWORD" && missing=1
          [ -z "${{ secrets.FTP_PROTOCOL }}" ] && echo "Missing required secret: FTP_PROTOCOL (ftp|ftps|sftp)" && missing=1
          [ -z "${{ secrets.FTP_PORT }}" ] && echo "Missing required secret: FTP_PORT (21 for ftp/ftps, 22 for sftp)" && missing=1
          [ -z "${{ secrets.FTP_REMOTE_DIR }}" ] && echo "Missing required secret: FTP_REMOTE_DIR (e.g. public_html/ or domains/tu-dominio/public_html/)" && missing=1
          if [ "$missing" -ne 0 ]; then
            echo "One or more required secrets are missing. Configure them in GitHub → Settings → Secrets and variables → Actions." >&2
            exit 1
          fi

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }} # ftp or ftps or sftp
          port: ${{ secrets.FTP_PORT }} # e.g. 21 for ftp/ftps, 22 for sftp
          local-dir: dist/
          server-dir: ${{ secrets.FTP_REMOTE_DIR }} # e.g. public_html/
          # WARNING: cleans the target directory before upload
          dangerous-clean-slate: true
          # Only keep built assets on the server
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
