name: Build and publish to deploy branch

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish dist to deploy branch
        env:
          REPO: ${{ github.repository }}
        run: |
          set -e
          rm -rf out && mkdir out
          cp -R dist/* out/
          cd out
          git init
          git checkout -b deploy
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Publish static build"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${REPO}.git
          git push --force origin deploy
